services:
  vscode:
    build: .
    image: latex-uestc-devcontainer
    # Acquire::Retries: 3
    volumes:
      - ../:/workspace
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory
      - ~/.ssh:/root/.ssh
      # For Windows without WSL, a copy will be made
      # from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history:z
    environment:
      - TZ=Asia/Shanghai
    entrypoint: ["zsh", "-c", "while sleep 1000; do :; done"]
 
